[asan] suppress the static variable leaks
sonic-net/sonic-sairedis pull request #1085
Opened 2022-07-21 08:35 UTC by Yakiv-Huryk

This is to suppress ASAN false positives for static variables.
For example, the ServiceMethodTable::m_slots is sometimes reported as leaked.

ASAN report example:
```c
Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7feb0d3f4647 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55b3be15e430 in declare_static<syncd::ServiceMethodTable::SlotBase, syncd::ServiceMethodTable::Slot, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9> syncd/ServiceMethodTable.cpp:74
    #2 0x55b3be15e430 in declare_static<syncd::ServiceMethodTable::SlotBase, syncd::ServiceMethodTable::Slot, 10> syncd/ServiceMethodTable.cpp:81
    #3 0x55b3be15e430 in __static_initialization_and_destruction_0 syncd/ServiceMethodTable.cpp:85
    #4 0x55b3be15e430 in _GLOBAL__sub_I_ServiceMethodTable.cpp syncd/ServiceMethodTable.cpp:121
```

2022-07-21 12:34 UTC, kcudnik requested changes

2022-07-21 15:48 UTC, Yakiv-Huryk commented on syncd/Asan.cpp
> +
It is rather a callback than a missing import. This is one of the ways to configure ASAN/LSAN. 
Another way is to have a file (e.g. supressions.txt) and pass a path to it via env variable options.
The 'callback' approach is simpler and allows to keep all the asan-related things in asan.cpp.
This also seems to be a more popular way to configure the suppressions (e.g. chromium does this).

2022-07-21 17:46 UTC, kcudnik submitted a review, later dismissed

2022-07-21 17:46 UTC, kcudnik commented
please fix build errors

2022-07-22 11:40 UTC, kcudnik approved these changes

2022-08-08 12:21 UTC, liat-grozovik commented
@kcudnik could you please help to merge?

2022-08-09 17:50 UTC, merged