[fastboot] Notify SAI that fastboot is done
sonic-net/sonic-sairedis pull request #1396
Opened 2024-06-17 02:47 UTC by Junchao-Mellanox

**Why I did this**

Notify SAI that fastboot is done

**How I did this**

Set SAI_SWITCH_ATTR_FAST_API_ENABLE to false when fastboot is done

**How I verify this**

Manual test

2024-06-17 02:51 UTC, Junchao-Mellanox commented
Hi @yxieca , @vaibhavhd , could you please kindly review it?

2024-06-17 05:42 UTC, kcudnik approved these changes

2024-06-17 05:43 UTC, kcudnik commented
Please fix errors

2024-06-17 07:00 UTC, stepanblyschak approved these changes

2024-06-17 07:48 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-sairedis

2024-06-17 07:48 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-sairedis

2024-06-20 22:57 UTC, yxieca commented
@adyeung can you get someone from Broadcom to assess this change?

2024-06-26 20:52 UTC, adyeung commented
@tushar-ty please help review

2024-06-27 01:29 UTC, Junchao-Mellanox commented
Hi, please hod on the review for a moment. I will need to update this PR.

2024-07-04 07:31 UTC, Junchao-Mellanox commented
Hi @tushar-ty @vishnushetty , could you please kindly provide comment?

2024-07-09 01:51 UTC, Junchao-Mellanox commented
Hi @adyeung, @tushar-ty, @vishnushetty, kindly reminder.

2024-07-17 21:20 UTC, adyeung commented
Adding @Prasanth-KV to help review

2024-07-22 15:32 UTC, Prasanth-KV requested changes

2024-07-23 01:28 UTC, Junchao-Mellanox commented on syncd/Syncd.cpp
> +                m_commandLineOptions->m_startType == SAI_START_TYPE_FAST_BOOT)
Hi @Prasanth-KV , thanks for the comment. We are here to understand if there is any vendor who does not support it. If you know any vendor who does not support it, could you please provide the vendor name? Also, I assume you are from Broadcom, does Broadcom support SAI_SWITCH_ATTR_FAST_API_ENABLE in this case?

2024-07-23 09:53 UTC, Prasanth-KV commented on syncd/Syncd.cpp
> +                m_commandLineOptions->m_startType == SAI_START_TYPE_FAST_BOOT)
Broadcom does not support SAI_SWITCH_ATTR_FAST_API_ENABLE. Also, Broadcom doesn't use start type command line option as of now and hence this won't affect Broadcom platforms currently. If SAI_SWITCH_ATTR_FAST_API_ENABLE is required for fast-boot case, it is better to add capability check and skip if not supported.

2024-07-23 09:54 UTC, Junchao-Mellanox commented on syncd/Syncd.cpp
> +                m_commandLineOptions->m_startType == SAI_START_TYPE_FAST_BOOT)
thanks! I have pushed the fix, the change will only affect mellanox platform.

2024-07-24 05:50 UTC, Prasanth-KV approved these changes

2024-07-24 07:19 UTC, liat-grozovik commented
@Junchao-Mellanox  can you check please the PR checker coverage issue?

2024-07-24 07:21 UTC, Junchao-Mellanox commented
> @Junchao-Mellanox can you check please the PR checker coverage issue?

Sure, working on it

2024-07-24 10:24 UTC, Junchao-Mellanox commented
The new test case passed locally, but failed in github checker, I will investigate.

2024-07-25 01:36 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-sairedis

2024-07-25 01:36 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-sairedis

2024-07-25 06:07 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-sairedis

2024-07-25 06:07 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-sairedis

2024-07-26 08:31 UTC, Junchao-Mellanox commented
Hi @kcudnik , could you please review and merge?

2024-07-27 19:52 UTC, kcudnik approved these changes

2024-07-28 10:50 UTC, liat-grozovik commented
@saiarcot895 could you please help to merge?

2024-07-30 09:14 UTC, dprital commented
Should be merged only after upstream of SAI version 2405.29.0.0.
@Junchao-Mellanox , please mention it on PR description

2024-08-05 01:40 UTC, Junchao-Mellanox commented
/azpw run Azure.sonic-sairedis

2024-08-05 01:40 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-sairedis

2024-09-03 08:38 UTC, liat-grozovik commented
@kcudnik can you please help to merge?

2024-09-09 14:01 UTC, liat-grozovik commented
@saiarcot895 @kcudnik kindly reminder to merge this one

2024-10-23 08:52 UTC, Junchao-Mellanox commented
Hi @kcudnik , could you please help merge this one?

2024-10-23 09:30 UTC, merged

2024-11-20 21:26 UTC, bingwang-ms commented
@Junchao-Mellanox Auto-cherry-pick seems not working on this PR. Can you please raise a PR to 202405 branch?

2024-11-21 06:34 UTC, Junchao-Mellanox commented
Backport PR: https://github.com/sonic-net/sonic-sairedis/pull/1468

2024-12-11 05:42 UTC, zhangyanzhao commented
proposed for 202411 release but cherry pick to 202405.